#!/usr/bin/env bash
# script Displays the contents of the file `/etc/passwd`.
#   this will Only displays the username, user id, and user home directory path.
while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
