#!/usr/bin/env bash
# this bash script Parses Apache log files in list format.
#   Will Groups visitors by IP and HTTP status code.
#   Displaysnumber of occurrences, IP, and HTTP status code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
